export interface Location {
  slug: string;
  name: string;
  state: string;
  region: string;
  nearby: string[];
  coordinates: { latitude: number; longitude: number };
  metaDescription: string;
  intro: string;
}

export const LOCATIONS: Location[] = [
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Navi Mumbai", "Thane", "Borivali", "Andheri", "Bandra", "Goregaon", "Malad", "Dadar"],
    coordinates: { latitude: 19.0760, longitude: 72.8777 },
    metaDescription: "Premium residential interior design in Mumbai. Transform your 1BHK, 2BHK or 3BHK into a timeless home with Bhumi Mistry Interiors.",
    intro: "Mumbai — the city that never sleeps deserves a home that lets you breathe. At Bhumi Mistry Interiors, we design homes that balance the energy of maximum city with the calm of thoughtfully curated spaces. From a compact 1BHK in Malad to a sprawling 3BHK in Bandra, every square foot is considered.",
  },
  {
    slug: "navi-mumbai",
    name: "Navi Mumbai",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Vashi", "Kharghar", "Nerul", "Panvel", "CBD Belapur", "Seawoods"],
    coordinates: { latitude: 19.0330, longitude: 73.0297 },
    metaDescription: "Best interior designer in Navi Mumbai. Expert home interior design for apartments and villas across Vashi, Kharghar, Nerul and Panvel.",
    intro: "Navi Mumbai's planned layouts deserve interiors that match their thoughtful architecture. Whether it is a sea-facing apartment in Kharghar or a penthouse in Nerul, our designs respect the structure while adding warmth, texture and personality.",
  },
  {
    slug: "thane",
    name: "Thane",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Mulund", "Dombivli", "Kalyan", "Bhiwandi", "Vasai"],
    coordinates: { latitude: 19.2183, longitude: 72.9781 },
    metaDescription: "Top interior designer in Thane. Custom home interiors for 1BHK, 2BHK and 3BHK flats with modern Indian aesthetics and turnkey execution.",
    intro: "Thane has emerged as one of Mumbai's most desirable residential hubs. Our team works extensively across Thane's sprawling apartment complexes, delivering interiors that feel expansive, light-filled, and deeply personal — from the living room to the last wardrobe.",
  },
  {
    slug: "borivali",
    name: "Borivali",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Kandivali", "Dahisar", "Malad", "Goregaon", "Mira Road"],
    coordinates: { latitude: 19.2265, longitude: 72.8577 },
    metaDescription: "Interior designer in Borivali — modern, budget-friendly and luxury home interior design for flats and bungalows across Borivali West and East.",
    intro: "Borivali homes often come with generous square footage and green views. Our approach enhances that natural advantage with warm materials, intelligent storage, and layouts that work for multi-generational families.",
  },
  {
    slug: "kandivali",
    name: "Kandivali",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Borivali", "Malad", "Dahisar", "Charkop", "Mira Road"],
    coordinates: { latitude: 19.2130, longitude: 72.8436 },
    metaDescription: "Affordable and premium interior designer in Kandivali. Specialising in 1BHK, 2BHK and 3BHK flat interiors with on-time delivery.",
    intro: "Kandivali offers a unique mix of established neighbourhoods and new developments. Our interiors for Kandivali homes focus on maximising natural light, creating flexible living spaces, and using materials that age beautifully.",
  },
  {
    slug: "malad",
    name: "Malad",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Kandivali", "Borivali", "Goregaon", "Andheri", "Mindspace"],
    coordinates: { latitude: 19.1850, longitude: 72.8418 },
    metaDescription: "Modern interior designer in Malad — complete home interiors for apartments in Malad West and East. Modular kitchen, wardrobe, living room and more.",
    intro: "Malad's skyline is transforming, and so are its homes. We design interiors that keep pace with the city's energy while creating sanctuaries of calm. From compact studios to spacious family apartments, every project gets our full attention.",
  },
  {
    slug: "andheri",
    name: "Andheri",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Malad", "Goregaon", "Bandra", "Juhu", "Powai", "Vile Parle"],
    coordinates: { latitude: 19.1197, longitude: 72.8464 },
    metaDescription: "Leading interior designer in Andheri. Premium residential interior design for apartments in Andheri West, East, Lokhandwala and Versova.",
    intro: "Andheri is the heart of Mumbai's western suburbs — a bustling hub where young families and professionals build their lives. Our interiors balance function with beauty, ensuring every home is as practical as it is stunning.",
  },
  {
    slug: "bandra",
    name: "Bandra",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Khar", "Santacruz", "Dadar", "Worli", "Andheri"],
    coordinates: { latitude: 19.0592, longitude: 72.8405 },
    metaDescription: "Premium interior designer in Bandra. Boutique home interior design for heritage apartments, new builds and penthouses in Bandra West and East.",
    intro: "Bandra has a soul — a mix of old-world charm and contemporary edge. Our designs for Bandra homes honour that character while introducing modern comforts, clean lines, and carefully chosen materials.",
  },
  {
    slug: "goregaon",
    name: "Goregaon",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Malad", "Andheri", "Jogeshwari", "Film City Road"],
    coordinates: { latitude: 19.1652, longitude: 72.8475 },
    metaDescription: "Best interior designer in Goregaon. Complete home interior solutions for 1BHK, 2BHK and 3BHK flats in Goregaon West and East.",
    intro: "Goregaon has grown into a self-contained residential destination with excellent connectivity. We design homes here that feel spacious and connected, with layouts that adapt to modern work-from-home needs and family life.",
  },
  {
    slug: "dahisar",
    name: "Dahisar",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Borivali", "Kandivali", "Mira Road", "National Park"],
    coordinates: { latitude: 19.2441, longitude: 72.8558 },
    metaDescription: "Interior designer in Dahisar — affordable and luxury home interior design. Specialising in apartment interiors, modular kitchens and wardrobes.",
    intro: "Dahisar sits at the green edge of Mumbai, close to the national park. Our interiors draw from that proximity to nature — using natural materials, earthy tones, and designs that bring the outside in.",
  },
  {
    slug: "mira-road",
    name: "Mira Road",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Mira Bhayandar", "Dahisar", "Borivali", "Bhayandar", "Vasai"],
    coordinates: { latitude: 19.2717, longitude: 72.8607 },
    metaDescription: "Top interior designer in Mira Road. Complete home interior design for new apartments and renovation projects across Mira Road and Bhayandar.",
    intro: "Mira Road has become a preferred destination for homebuyers seeking space and affordability. We help Mira Road residents turn their new apartments into warm, functional homes with smart layouts and beautiful finishes.",
  },
  {
    slug: "mira-bhayandar",
    name: "Mira Bhayandar",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Mira Road", "Bhayandar", "Vasai", "Dahisar"],
    coordinates: { latitude: 19.2930, longitude: 72.8570 },
    metaDescription: "Interior designer in Mira Bhayandar. Budget to premium home interior design for apartments and villas in the Mira Bhayandar region.",
    intro: "Mira Bhayandar offers some of the best value in the Mumbai metropolitan region. Our clients here appreciate designs that are practical, beautiful, and delivered on budget — without compromising on quality.",
  },
  {
    slug: "vasai",
    name: "Vasai",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Virar", "Mira Bhayandar", "Nalasopara", "Palghar"],
    coordinates: { latitude: 19.3652, longitude: 72.8192 },
    metaDescription: "Professional interior designer in Vasai. Custom home interiors for apartments, row houses and bungalows in Vasai West and East.",
    intro: "Vasai is experiencing rapid growth, with new residential projects reshaping the landscape. We help homeowners in Vasai create interiors that maximise space, reflect their personality, and stand the test of time.",
  },
  {
    slug: "virar",
    name: "Virar",
    state: "Maharashtra",
    region: "Mumbai Metropolitan Region",
    nearby: ["Vasai", "Nalasopara", "Palghar", "Mira Road"],
    coordinates: { latitude: 19.4606, longitude: 72.8029 },
    metaDescription: "Best interior designer in Virar. Affordable and premium interior design services for 1BHK, 2BHK and 3BHK homes across Virar.",
    intro: "Virar represents the new frontier of Mumbai metropolitan living. Our interior design solutions for Virar homes focus on creating maximum impact within practical budgets, helping every home feel thoughtfully designed.",
  },
  {
    slug: "powai",
    name: "Powai",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Andheri", "Kanjurmarg", "Vikhroli", "Bhandup", "Chandivali"],
    coordinates: { latitude: 19.1176, longitude: 72.8990 },
    metaDescription: "Premium interior designer in Powai. Luxury home interiors for apartments in Powai's premium complexes including Hiranandani Gardens.",
    intro: "Powai is one of Mumbai's most desirable addresses. Our interiors for Powai homes match the sophistication of the neighbourhood — clean lines, premium materials, and a seamless flow between indoor and outdoor spaces.",
  },
  {
    slug: "ghatkopar",
    name: "Ghatkopar",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Chembur", "Vikhroli", "Powai", "Mulund", "Bhandup"],
    coordinates: { latitude: 19.0865, longitude: 72.9082 },
    metaDescription: "Interior designer in Ghatkopar — complete home interiors for 1BHK, 2BHK and 3BHK flats. Modern Indian designs at honest prices.",
    intro: "Ghatkopar combines excellent connectivity with vibrant neighbourhood living. Our design philosophy for Ghatkopar homes blends modern aesthetics with practical layouts that suit the needs of growing families.",
  },
  {
    slug: "chembur",
    name: "Chembur",
    state: "Maharashtra",
    region: "Mumbai Suburban",
    nearby: ["Ghatkopar", "Bandra", "Worli", "Kurla", "Govandi"],
    coordinates: { latitude: 19.0581, longitude: 72.9002 },
    metaDescription: "Expert interior designer in Chembur. Premium residential interior design for apartments and bungalows in Chembur, Diamond Garden and surrounding areas.",
    intro: "Chembur has a distinct character — green, well-planned, and family-oriented. Our designs for Chembur homes emphasise openness, natural light, and materials that bring warmth to every room.",
  },
  {
    slug: "dadar",
    name: "Dadar",
    state: "Maharashtra",
    region: "Mumbai City",
    nearby: ["Prabhadevi", "Worli", "Matunga", "Mahim", "Shivaji Park"],
    coordinates: { latitude: 19.0178, longitude: 72.8478 },
    metaDescription: "Interior designer in Dadar. Beautiful home interiors for heritage apartments and modern flats in Dadar West, East and Shivaji Park.",
    intro: "Dadar is the cultural heart of Mumbai. Our work in Dadar ranges from heritage apartment restorations in Shivaji Park to contemporary interiors in new developments — always respecting the neighbourhood's unique character.",
  },
  {
    slug: "vashi",
    name: "Vashi",
    state: "Maharashtra",
    region: "Navi Mumbai",
    nearby: ["Kharghar", "Nerul", "CBD Belapur", "Sanpada", "Seawoods"],
    coordinates: { latitude: 19.0744, longitude: 72.9955 },
    metaDescription: "Top interior designer in Vashi. Complete home interior solutions for apartments in Vashi, Navi Mumbai. Modular kitchen, wardrobe and living room design.",
    intro: "Vashi was Navi Mumbai's first node and remains one of its most sought-after locations. Our interiors for Vashi homes combine functional layouts with sophisticated design, creating spaces that are both beautiful and liveable.",
  },
  {
    slug: "kharghar",
    name: "Kharghar",
    state: "Maharashtra",
    region: "Navi Mumbai",
    nearby: ["Nerul", "Panvel", "Vashi", "CBD Belapur", "Uran"],
    coordinates: { latitude: 19.0473, longitude: 73.0622 },
    metaDescription: "Best interior designer in Kharghar. Luxury and budget home interiors for apartments in Kharghar, Navi Mumbai — modern designs with timely delivery.",
    intro: "Kharghar has emerged as a premium residential destination with its hill views and planned infrastructure. Our interior design solutions for Kharghar homes focus on maximising views, creating open layouts, and using premium materials.",
  },
  {
    slug: "nerul",
    name: "Nerul",
    state: "Maharashtra",
    region: "Navi Mumbai",
    nearby: ["Kharghar", "Vashi", "CBD Belapur", "Seawoods", "Panvel"],
    coordinates: { latitude: 19.0369, longitude: 73.0235 },
    metaDescription: "Interior designer in Nerul. Modern home interiors for apartments in Nerul, Navi Mumbai. Specialists in 1BHK, 2BHK and 3BHK design.",
    intro: "Nerul offers a relaxed, green lifestyle away from the city's chaos. Our designs for Nerul homes embrace that calm — using neutral palettes, natural textures, and layouts that promote easy everyday living.",
  },
  {
    slug: "panvel",
    name: "Panvel",
    state: "Maharashtra",
    region: "Navi Mumbai",
    nearby: ["Kharghar", "Kamothe", "Kalamboli", "Uran", "Nerul"],
    coordinates: { latitude: 18.9899, longitude: 73.1165 },
    metaDescription: "Interior designer in Panvel. Affordable and premium home interior design for apartments, row houses and villas in Panvel and surrounding areas.",
    intro: "Panvel is shaping up as the next big residential hub in the Mumbai region. Our team creates interiors for Panvel homes that are future-ready — flexible layouts, durable materials, and designs that evolve with your family.",
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}

export const LOCATION_SLUGS = LOCATIONS.map((l) => l.slug);
